### PR TITLE
Add 36 languages translations

### PR DESCRIPTION
**Pull request by calcitem**
## :scroll: Description

* Add 36 languages translations
* Remove example/pubspec.lock

## :bulb: Motivation and Context

* Some users can't read English and need to support more languages.

* pubspec.lock is ignored by .gitignore. url will be rewritten if PUB_HOSTED_URL is modified. So remove this file.

## :green_heart: How did you test it?

* Change the device language and observe if the display is normal and if the text is too long.
* Delete pubspec.lock and recompile successfully, so deleting this file does not affect the compilation.

## :pencil: Checklist

- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [ ] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps

Except for Chinese, the translation cannot be guaranteed to be absolutely correct and needs to be further optimized by Native Speaker.

### CODE REVIEW

**Comment by ueman** [comment]
Hey, thanks for your PR.
Are those autogenerated translations?

**Comment by calcitem** [comment]
I should thank you. 

I just added the feedback function to my App and received an user feedback the next day. The user said that the new function added in this update is great and will have the effect of enticing people to give feedback. I said this feature should be attributed to you!  

At present, it is not automatically generated. I don't know if it can be managed with arb files.  Because I am not familiar with component debugging, I just simply copy and paste similar code.

**Comment by ueman** [comment]
That's great to hear. I'm really happy it has a good impact for you.

Let me clarify my question:
Are these translations created by services like Google Translate or similar?

**Comment by calcitem** [comment]
These translations are first translated from German into the target language using DeepL. If the translation result is too long, it is expected to affect the aesthetics, and use Google Translate instead.  For languages ​​not supported by DeepL, use Google Translate. Japanese and Korean are translated from Chinese.

**Comment by calcitem** [comment]
https://github.com/ueman/feedback/pull/140/commits/7b12c20baa35d2dd2bf64e2a35e2837448b5d1c6 is better. So i close this PR.

**Pull request closed without merging**
