### PR TITLE
Update translation.dart Added Arabic Language

### PR DESCRIPTION
**Pull request by ajnaf**
Added Arabic Language

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

### CODE REVIEW

**Comment by calcitem** [comment]
This PR is better. So I close https://github.com/ueman/feedback/pull/97

**Comment by ajnaf** [comment]
When will you publish it?

**Comment by calcitem** [comment]
Jun 27, 2021

**Comment by ueman** [comment]
Thanks! I'll do a release later this day.

**Review by ueman — APPROVED** [review]

**Comment by ajnaf** [comment]
Thanks

**Comment by ajnaf** [comment]
Thanks

**Pull request merged**
